### PR TITLE
Support time series in PlyType

### PR DESCRIPTION
**Pull request by pengz-imply**
This PR makes the necessary changes to support the TIME_SERIES type.

### CODE REVIEW

**Review by jgoz — COMMENTED** [review]
This looks fine, but I wonder if it is complete. Do we need a TimeSeries datatype? And should it get included in Dataset, formatting, inflating, etc.?

I don't know the answer to these questions, but the last new type we added, `IP`, included a datatype `Ip`.

**Comment by pengz-imply** [comment]
> This looks fine, but I wonder if it is complete. Do we need a TimeSeries datatype? And should it get included in Dataset, formatting, inflating, etc.?
> 
> I don't know the answer to these questions, but the last new type we added, `IP`, included a datatype `Ip`.

Good question! I'm not very familiar with `Dataset`, but from what I found, it is related to querying data using Plywood. Currently in Pivot, querying time series data is only supported for SQL query construction using `druid-query-toolkit` without needing Plywood. I don't have a plan for supporting querying time series data in Plywood, Therefore, I only made minimal changes in Plywood for Pivot to recognize ingested time series columns as "TIME_SERIES" from introspection, and that's the extent of the purpose.

**Comment by jgoz** [comment]
@pengz-imply Published as 0.35.5

**Comment by pengz-imply** [comment]
> @pengz-imply Published as 0.35.5

Thank you!

**Pull request merged**
